version: v2beta1
name: kortexa

pipelines:
  dev:
    run: |-
      build_images --all
      create_deployments --all
      start_dev backend
  deploy:
    run: |-
      build_images --all
      create_deployments --all

images:
  backend:
    image: kortexa-backend
    context: .\backend
    dockerfile: .\backend\Dockerfile

deployments:
  backend:
    helm:
      releaseName: kortexa
      chart:
        name: .\k8s\helm\backend
      values:
        image:
          repository: ${runtime.images.backend.image}
          tag: ${runtime.images.backend.tag}
      upgradeArgs:
        - --create-namespace

dev:
  backend:
    imageSelector: kortexa-backend
    devImage: ${runtime.images.backend.image}:${runtime.images.backend.tag}
    sync:
      - path: .\backend\src:/app/src
      - path: .\backend\manage.py:/app/manage.py
    ports:
      - port: 8000
    terminal:
      command: /bin/sh (for monorepos)
